export const PROJECTS = [
  {
    id: 'mambo',
    name: 'mambo',
    tail: 'v0.7',
    status: 'active',
    statusLabel: 'flagship · v0.7',
    tag: 'Keyboard-driven desktop database client.',
    desc: 'Connect, query, browse without leaving the home row. macOS & Linux.',
    chips: ['postgres', 'mysql', 'mariadb', 'mongodb', 'redis', 'sqlite', 'clickhouse', 'duckdb', 'elasticsearch', 'cassandra'],
    repo: 'trymambo.app',
    href: 'https://trymambo.app',
    kind: 'desktop tool',
  },
  {
    id: 'blurt',
    name: 'blurt.sh',
    tail: 'live',
    status: 'active',
    statusLabel: 'live',
    tag: 'The simplest way to publish on the web.',
    desc: 'Push markdown, send an email, or just write. Your blog is live.',
    chips: ['markdown', 'email-to-publish', 'rss', 'zero-config'],
    repo: 'blurt.sh',
    href: 'https://blurt.sh',
    kind: 'writing tool',
  },
  {
    id: 'quietdash',
    name: 'quietdash.com',
    tail: 'wip',
    status: 'wip',
    statusLabel: 'wip',
    tag: 'A quiet dashboard.',
    desc: "Numbers that matter, nothing that doesn't. The metrics screen you'd actually look at.",
    chips: ['dashboard', 'low-signal-loss', 'single-screen'],
    repo: 'quietdash.com',
    href: 'https://quietdash.com',
    kind: 'saas',
  },
  {
    id: 'minihabits',
    name: 'minihabits',
    tail: 'archived',
    status: 'archived',
    statusLabel: 'discontinued',
    tag: 'A minimalist habit tracking app.',
    desc: 'One screen. Tap. Done. Streak. No onboarding, no settings, no notifications.',
    chips: ['habits', 'mobile-first', 'no-onboarding'],
    repo: 'minihabits.co',
    href: 'https://minihabits.co',
    kind: 'mobile app',
  },
];
